version: '3.8'

services:
  bear-server:
    image: snowyfield1906/bear-server:latest
    ports:
      - '7777:7777'
    environment:
      - HOST=0.0.0.0
      - PORT=7777
      - MONGO_URL=mongodb+srv://Hayden:Hayden%40189389@bc.y0mzx.mongodb.net/blog?retryWrites=true&w=majority
